services:
  livekit:
    image: livekit/livekit-server:v1.8.3
    ports:
      - "7880:7880"
      - "7881:7881"
      - "7882:7882"
      - "50000-50100:50000-50100/udp"
    volumes:
      - ./livekit.yaml:/etc/livekit.yaml
    command: --config /etc/livekit.yaml
