package com.shyden.shytalk.core.util

data class Country(
    val code: String,
    val name: String,
    val flagEmoji: String,
)

fun flagEmojiForCode(code: String): String {
    if (code.length != 2) return ""
    val first = 0x1F1E6 + (code[0].uppercaseChar() - 'A')
    val second = 0x1F1E6 + (code[1].uppercaseChar() - 'A')
    return codePointToString(first) + codePointToString(second)
}

/** Converts a Unicode code point to a String, handling supplementary (non-BMP) characters. */
private fun codePointToString(codePoint: Int): String =
    if (codePoint <= 0xFFFF) {
        codePoint.toChar().toString()
    } else {
        val high = ((codePoint - 0x10000) shr 10) + 0xD800
        val low = ((codePoint - 0x10000) and 0x3FF) + 0xDC00
        "${high.toChar()}${low.toChar()}"
    }

private val countryByCode: Map<String, Country> by lazy { countries.associateBy { it.code } }

fun countryNameForCode(code: String): String? = countryByCode[code.uppercase()]?.name

val countries: List<Country> =
    listOf(
        Country("AF", "Afghanistan", flagEmojiForCode("AF")),
        Country("AL", "Albania", flagEmojiForCode("AL")),
        Country("DZ", "Algeria", flagEmojiForCode("DZ")),
        Country("AD", "Andorra", flagEmojiForCode("AD")),
        Country("AO", "Angola", flagEmojiForCode("AO")),
        Country("AG", "Antigua and Barbuda", flagEmojiForCode("AG")),
        Country("AR", "Argentina", flagEmojiForCode("AR")),
        Country("AM", "Armenia", flagEmojiForCode("AM")),
        Country("AU", "Australia", flagEmojiForCode("AU")),
        Country("AT", "Austria", flagEmojiForCode("AT")),
        Country("AZ", "Azerbaijan", flagEmojiForCode("AZ")),
        Country("BS", "Bahamas", flagEmojiForCode("BS")),
        Country("BH", "Bahrain", flagEmojiForCode("BH")),
        Country("BD", "Bangladesh", flagEmojiForCode("BD")),
        Country("BB", "Barbados", flagEmojiForCode("BB")),
        Country("BY", "Belarus", flagEmojiForCode("BY")),
        Country("BE", "Belgium", flagEmojiForCode("BE")),
        Country("BZ", "Belize", flagEmojiForCode("BZ")),
        Country("BJ", "Benin", flagEmojiForCode("BJ")),
        Country("BT", "Bhutan", flagEmojiForCode("BT")),
        Country("BO", "Bolivia", flagEmojiForCode("BO")),
        Country("BA", "Bosnia and Herzegovina", flagEmojiForCode("BA")),
        Country("BW", "Botswana", flagEmojiForCode("BW")),
        Country("BR", "Brazil", flagEmojiForCode("BR")),
        Country("BN", "Brunei", flagEmojiForCode("BN")),
        Country("BG", "Bulgaria", flagEmojiForCode("BG")),
        Country("BF", "Burkina Faso", flagEmojiForCode("BF")),
        Country("BI", "Burundi", flagEmojiForCode("BI")),
        Country("CV", "Cabo Verde", flagEmojiForCode("CV")),
        Country("KH", "Cambodia", flagEmojiForCode("KH")),
        Country("CM", "Cameroon", flagEmojiForCode("CM")),
        Country("CA", "Canada", flagEmojiForCode("CA")),
        Country("CF", "Central African Republic", flagEmojiForCode("CF")),
        Country("TD", "Chad", flagEmojiForCode("TD")),
        Country("CL", "Chile", flagEmojiForCode("CL")),
        Country("CN", "China", flagEmojiForCode("CN")),
        Country("CO", "Colombia", flagEmojiForCode("CO")),
        Country("KM", "Comoros", flagEmojiForCode("KM")),
        Country("CG", "Congo", flagEmojiForCode("CG")),
        Country("CR", "Costa Rica", flagEmojiForCode("CR")),
        Country("HR", "Croatia", flagEmojiForCode("HR")),
        Country("CU", "Cuba", flagEmojiForCode("CU")),
        Country("CY", "Cyprus", flagEmojiForCode("CY")),
        Country("CZ", "Czech Republic", flagEmojiForCode("CZ")),
        Country("DK", "Denmark", flagEmojiForCode("DK")),
        Country("DJ", "Djibouti", flagEmojiForCode("DJ")),
        Country("DM", "Dominica", flagEmojiForCode("DM")),
        Country("DO", "Dominican Republic", flagEmojiForCode("DO")),
        Country("EC", "Ecuador", flagEmojiForCode("EC")),
        Country("EG", "Egypt", flagEmojiForCode("EG")),
        Country("SV", "El Salvador", flagEmojiForCode("SV")),
        Country("GQ", "Equatorial Guinea", flagEmojiForCode("GQ")),
        Country("ER", "Eritrea", flagEmojiForCode("ER")),
        Country("EE", "Estonia", flagEmojiForCode("EE")),
        Country("SZ", "Eswatini", flagEmojiForCode("SZ")),
        Country("ET", "Ethiopia", flagEmojiForCode("ET")),
        Country("FJ", "Fiji", flagEmojiForCode("FJ")),
        Country("FI", "Finland", flagEmojiForCode("FI")),
        Country("FR", "France", flagEmojiForCode("FR")),
        Country("GA", "Gabon", flagEmojiForCode("GA")),
        Country("GM", "Gambia", flagEmojiForCode("GM")),
        Country("GE", "Georgia", flagEmojiForCode("GE")),
        Country("DE", "Germany", flagEmojiForCode("DE")),
        Country("GH", "Ghana", flagEmojiForCode("GH")),
        Country("GR", "Greece", flagEmojiForCode("GR")),
        Country("GD", "Grenada", flagEmojiForCode("GD")),
        Country("GT", "Guatemala", flagEmojiForCode("GT")),
        Country("GN", "Guinea", flagEmojiForCode("GN")),
        Country("GW", "Guinea-Bissau", flagEmojiForCode("GW")),
        Country("GY", "Guyana", flagEmojiForCode("GY")),
        Country("HT", "Haiti", flagEmojiForCode("HT")),
        Country("HN", "Honduras", flagEmojiForCode("HN")),
        Country("HU", "Hungary", flagEmojiForCode("HU")),
        Country("IS", "Iceland", flagEmojiForCode("IS")),
        Country("IN", "India", flagEmojiForCode("IN")),
        Country("ID", "Indonesia", flagEmojiForCode("ID")),
        Country("IR", "Iran", flagEmojiForCode("IR")),
        Country("IQ", "Iraq", flagEmojiForCode("IQ")),
        Country("IE", "Ireland", flagEmojiForCode("IE")),
        Country("IL", "Israel", flagEmojiForCode("IL")),
        Country("IT", "Italy", flagEmojiForCode("IT")),
        Country("JM", "Jamaica", flagEmojiForCode("JM")),
        Country("JP", "Japan", flagEmojiForCode("JP")),
        Country("JO", "Jordan", flagEmojiForCode("JO")),
        Country("KZ", "Kazakhstan", flagEmojiForCode("KZ")),
        Country("KE", "Kenya", flagEmojiForCode("KE")),
        Country("KI", "Kiribati", flagEmojiForCode("KI")),
        Country("KW", "Kuwait", flagEmojiForCode("KW")),
        Country("KG", "Kyrgyzstan", flagEmojiForCode("KG")),
        Country("LA", "Laos", flagEmojiForCode("LA")),
        Country("LV", "Latvia", flagEmojiForCode("LV")),
        Country("LB", "Lebanon", flagEmojiForCode("LB")),
        Country("LS", "Lesotho", flagEmojiForCode("LS")),
        Country("LR", "Liberia", flagEmojiForCode("LR")),
        Country("LY", "Libya", flagEmojiForCode("LY")),
        Country("LI", "Liechtenstein", flagEmojiForCode("LI")),
        Country("LT", "Lithuania", flagEmojiForCode("LT")),
        Country("LU", "Luxembourg", flagEmojiForCode("LU")),
        Country("MG", "Madagascar", flagEmojiForCode("MG")),
        Country("MW", "Malawi", flagEmojiForCode("MW")),
        Country("MY", "Malaysia", flagEmojiForCode("MY")),
        Country("MV", "Maldives", flagEmojiForCode("MV")),
        Country("ML", "Mali", flagEmojiForCode("ML")),
        Country("MT", "Malta", flagEmojiForCode("MT")),
        Country("MH", "Marshall Islands", flagEmojiForCode("MH")),
        Country("MR", "Mauritania", flagEmojiForCode("MR")),
        Country("MU", "Mauritius", flagEmojiForCode("MU")),
        Country("MX", "Mexico", flagEmojiForCode("MX")),
        Country("FM", "Micronesia", flagEmojiForCode("FM")),
        Country("MD", "Moldova", flagEmojiForCode("MD")),
        Country("MC", "Monaco", flagEmojiForCode("MC")),
        Country("MN", "Mongolia", flagEmojiForCode("MN")),
        Country("ME", "Montenegro", flagEmojiForCode("ME")),
        Country("MA", "Morocco", flagEmojiForCode("MA")),
        Country("MZ", "Mozambique", flagEmojiForCode("MZ")),
        Country("MM", "Myanmar", flagEmojiForCode("MM")),
        Country("NA", "Namibia", flagEmojiForCode("NA")),
        Country("NR", "Nauru", flagEmojiForCode("NR")),
        Country("NP", "Nepal", flagEmojiForCode("NP")),
        Country("NL", "Netherlands", flagEmojiForCode("NL")),
        Country("NZ", "New Zealand", flagEmojiForCode("NZ")),
        Country("NI", "Nicaragua", flagEmojiForCode("NI")),
        Country("NE", "Niger", flagEmojiForCode("NE")),
        Country("NG", "Nigeria", flagEmojiForCode("NG")),
        Country("KP", "North Korea", flagEmojiForCode("KP")),
        Country("MK", "North Macedonia", flagEmojiForCode("MK")),
        Country("NO", "Norway", flagEmojiForCode("NO")),
        Country("OM", "Oman", flagEmojiForCode("OM")),
        Country("PK", "Pakistan", flagEmojiForCode("PK")),
        Country("PW", "Palau", flagEmojiForCode("PW")),
        Country("PS", "Palestine", flagEmojiForCode("PS")),
        Country("PA", "Panama", flagEmojiForCode("PA")),
        Country("PG", "Papua New Guinea", flagEmojiForCode("PG")),
        Country("PY", "Paraguay", flagEmojiForCode("PY")),
        Country("PE", "Peru", flagEmojiForCode("PE")),
        Country("PH", "Philippines", flagEmojiForCode("PH")),
        Country("PL", "Poland", flagEmojiForCode("PL")),
        Country("PT", "Portugal", flagEmojiForCode("PT")),
        Country("QA", "Qatar", flagEmojiForCode("QA")),
        Country("RO", "Romania", flagEmojiForCode("RO")),
        Country("RU", "Russia", flagEmojiForCode("RU")),
        Country("RW", "Rwanda", flagEmojiForCode("RW")),
        Country("KN", "Saint Kitts and Nevis", flagEmojiForCode("KN")),
        Country("LC", "Saint Lucia", flagEmojiForCode("LC")),
        Country("VC", "Saint Vincent and the Grenadines", flagEmojiForCode("VC")),
        Country("WS", "Samoa", flagEmojiForCode("WS")),
        Country("SM", "San Marino", flagEmojiForCode("SM")),
        Country("ST", "Sao Tome and Principe", flagEmojiForCode("ST")),
        Country("SA", "Saudi Arabia", flagEmojiForCode("SA")),
        Country("SN", "Senegal", flagEmojiForCode("SN")),
        Country("RS", "Serbia", flagEmojiForCode("RS")),
        Country("SC", "Seychelles", flagEmojiForCode("SC")),
        Country("SL", "Sierra Leone", flagEmojiForCode("SL")),
        Country("SG", "Singapore", flagEmojiForCode("SG")),
        Country("SK", "Slovakia", flagEmojiForCode("SK")),
        Country("SI", "Slovenia", flagEmojiForCode("SI")),
        Country("SB", "Solomon Islands", flagEmojiForCode("SB")),
        Country("SO", "Somalia", flagEmojiForCode("SO")),
        Country("ZA", "South Africa", flagEmojiForCode("ZA")),
        Country("KR", "South Korea", flagEmojiForCode("KR")),
        Country("SS", "South Sudan", flagEmojiForCode("SS")),
        Country("ES", "Spain", flagEmojiForCode("ES")),
        Country("LK", "Sri Lanka", flagEmojiForCode("LK")),
        Country("SD", "Sudan", flagEmojiForCode("SD")),
        Country("SR", "Suriname", flagEmojiForCode("SR")),
        Country("SE", "Sweden", flagEmojiForCode("SE")),
        Country("CH", "Switzerland", flagEmojiForCode("CH")),
        Country("SY", "Syria", flagEmojiForCode("SY")),
        Country("TW", "Taiwan", flagEmojiForCode("TW")),
        Country("TJ", "Tajikistan", flagEmojiForCode("TJ")),
        Country("TZ", "Tanzania", flagEmojiForCode("TZ")),
        Country("TH", "Thailand", flagEmojiForCode("TH")),
        Country("TL", "Timor-Leste", flagEmojiForCode("TL")),
        Country("TG", "Togo", flagEmojiForCode("TG")),
        Country("TO", "Tonga", flagEmojiForCode("TO")),
        Country("TT", "Trinidad and Tobago", flagEmojiForCode("TT")),
        Country("TN", "Tunisia", flagEmojiForCode("TN")),
        Country("TR", "Turkey", flagEmojiForCode("TR")),
        Country("TM", "Turkmenistan", flagEmojiForCode("TM")),
        Country("TV", "Tuvalu", flagEmojiForCode("TV")),
        Country("UG", "Uganda", flagEmojiForCode("UG")),
        Country("UA", "Ukraine", flagEmojiForCode("UA")),
        Country("AE", "United Arab Emirates", flagEmojiForCode("AE")),
        Country("GB", "United Kingdom", flagEmojiForCode("GB")),
        Country("US", "United States", flagEmojiForCode("US")),
        Country("UY", "Uruguay", flagEmojiForCode("UY")),
        Country("UZ", "Uzbekistan", flagEmojiForCode("UZ")),
        Country("VU", "Vanuatu", flagEmojiForCode("VU")),
        Country("VA", "Vatican City", flagEmojiForCode("VA")),
        Country("VE", "Venezuela", flagEmojiForCode("VE")),
        Country("VN", "Vietnam", flagEmojiForCode("VN")),
        Country("YE", "Yemen", flagEmojiForCode("YE")),
        Country("ZM", "Zambia", flagEmojiForCode("ZM")),
        Country("ZW", "Zimbabwe", flagEmojiForCode("ZW")),
    )
