/**
 * iOS Pods integration regression pin.
 *
 * Release run 26367863711 (PR #819, chore: release v0.97.6) failed
 * with: `error: Unable to find module dependency: 'FirebaseCore'
 * (in target 'iosAppTests' from project 'iosApp')`.
 *
 * Root cause: the iOS-local Phase 3.3+3.4 fix (commit c2101fc3216,
 * branch ios-local/3-3-3-4-combined) was authored but NEVER merged
 * to main. Without it, the Podfile lacks both:
 *   1. The `project` directive that maps Debug-Local / Release-Local
 *      to debug/release. Without this, CocoaPods refuses to integrate
 *      because it sees Local configs with empty SWIFT_VERSION (the
 *      project-level Local configs inherit from Local.xcconfig which
 *      doesn't define SWIFT_VERSION).
 *   2. The nested `target 'iosAppTests' do inherit! :search_paths
 *      end` block. Without this, iosAppTests has no Pods xcconfig
 *      integration. The test target uses `@testable import iosApp`,
 *      which requires resolving iosApp's transitive imports
 *      (FirebaseCore, FirebaseMessaging, GoogleSignIn, LiveKitClient)
 *      to type-check the import. xcodebuild build-for-testing fails
 *      before any test runs.
 *
 * Plus the project-level Debug-Local + Release-Local XCBuildConfigurations
 * must carry SWIFT_VERSION = 5.0 explicitly — CocoaPods enumerates ALL
 * project configs when validating SWIFT_VERSION uniqueness per target,
 * and an empty inherit on a Local config causes "There may only be up
 * to 1 unique SWIFT_VERSION per target" even on targets that don't
 * directly use Local configs.
 *
 * This test pins all 4 contract elements so a future Podfile cleanup
 * or pbxproj refactor that drops any of them fails CI immediately,
 * BEFORE the release workflow hits the iOS build.
 */

const fs = require('fs');
const path = require('path');

const REPO_ROOT = path.resolve(__dirname, '../../..');
const PODFILE = path.join(REPO_ROOT, 'iosApp/Podfile');
const PBXPROJ = path.join(REPO_ROOT, 'iosApp/iosApp.xcodeproj/project.pbxproj');

describe('iOS Pods integration — Podfile contract', () => {
  let PODFILE_SRC;
  beforeAll(() => {
    PODFILE_SRC = fs.readFileSync(PODFILE, 'utf8');
  });

  test('declares `project` directive mapping Debug-Local + Release-Local', () => {
    // CocoaPods needs to know how to treat the Local configs — without
    // this directive, SWIFT_VERSION resolution explodes on integration.
    expect(PODFILE_SRC).toMatch(/project ['"]iosApp\.xcodeproj['"]/);
    expect(PODFILE_SRC).toMatch(/['"]Debug-Local['"]\s*=>\s*:debug/);
    expect(PODFILE_SRC).toMatch(/['"]Release-Local['"]\s*=>\s*:release/);
  });

  test('declares nested `target "iosAppTests"` block with inherit! :search_paths', () => {
    // iosAppTests has @testable import iosApp which requires resolving
    // Firebase/LiveKit modules at build-for-testing. Without this
    // nested target, the test bundle can't find the modules.
    expect(PODFILE_SRC).toMatch(/target ['"]iosAppTests['"]\s+do/);
    // The inherit must be specifically :search_paths — re-embedding
    // (:complete or default) would duplicate-symbol since iosApp.app
    // already links them and TEST_HOST loads that.
    const inheritMatch = PODFILE_SRC.match(/target ['"]iosAppTests['"]\s+do\s+inherit!\s+:search_paths\s+end/);
    expect(inheritMatch).not.toBeNull();
  });

  test('iosAppTests target block is NESTED inside iosApp block', () => {
    // The nested form ensures iosAppTests shares the parent's Pods
    // workspace integration. A standalone top-level `target
    // 'iosAppTests'` would not get the inheritance.
    const iosAppOpen = PODFILE_SRC.indexOf("target 'iosApp' do");
    const iosAppTests = PODFILE_SRC.indexOf("target 'iosAppTests' do");
    expect(iosAppOpen).toBeGreaterThan(-1);
    expect(iosAppTests).toBeGreaterThan(iosAppOpen);
    // The `end` that closes iosApp must come AFTER iosAppTests block.
    // Trace by finding the last `end` in the file — that's iosApp's
    // closing `end`.
    const ends = [...PODFILE_SRC.matchAll(/^end$/gm)].map((m) => m.index);
    const lastEnd = ends[ends.length - 1];
    expect(lastEnd).toBeGreaterThan(iosAppTests);
  });
});

describe('iOS Pods integration — pbxproj contract', () => {
  let PBXPROJ_SRC;
  beforeAll(() => {
    PBXPROJ_SRC = fs.readFileSync(PBXPROJ, 'utf8');
  });

  test('Pods-iosAppTests.debug.xcconfig file reference exists', () => {
    // Generated by `pod install` after the Podfile has the nested
    // iosAppTests target.
    expect(PBXPROJ_SRC).toMatch(/Pods-iosAppTests\.debug\.xcconfig/);
  });

  test('Pods-iosAppTests.release.xcconfig file reference exists', () => {
    expect(PBXPROJ_SRC).toMatch(/Pods-iosAppTests\.release\.xcconfig/);
  });

  test('iosAppTests Debug + Release configs have baseConfigurationReference pointing at Pods xcconfigs', () => {
    // Without baseConfigurationReference, xcodebuild can't find the
    // Pods framework search paths — same failure mode as release
    // run 26367863711.
    expect(PBXPROJ_SRC).toMatch(
      /baseConfigurationReference = [A-F0-9]+ \/\* Pods-iosAppTests\.debug\.xcconfig \*\//,
    );
    expect(PBXPROJ_SRC).toMatch(
      /baseConfigurationReference = [A-F0-9]+ \/\* Pods-iosAppTests\.release\.xcconfig \*\//,
    );
  });

  test('project-level Debug-Local + Release-Local configs both declare SWIFT_VERSION = 5.0', () => {
    // CocoaPods enumerates ALL project-level configs when validating
    // SWIFT_VERSION uniqueness. An empty Swift on a Local config
    // breaks pod install with the multi-Swift-version error.
    // We match the buildSettings block (between the config-id comment
    // and `name = "<config>";`) for the SWIFT_VERSION line.
    function configContainsSwiftVersion(configName) {
      // Match a block that starts with `name = "<config>";` and walk
      // backwards to find SWIFT_VERSION = 5.0 within the preceding
      // buildSettings braces. Simpler: capture the full XCBuildConfiguration
      // block by matching from `isa = XCBuildConfiguration;` to the
      // closing `name = "<config>";`.
      const blockRx = new RegExp(
        `isa = XCBuildConfiguration;[\\s\\S]*?name = "${configName}";`,
        'g',
      );
      const blocks = [...PBXPROJ_SRC.matchAll(blockRx)].map((m) => m[0]);
      // There are TWO Debug-Local blocks (project-level + iosApp target);
      // ALL must have SWIFT_VERSION = 5.0.
      expect(blocks.length).toBeGreaterThan(0);
      for (const block of blocks) {
        expect(block).toMatch(/SWIFT_VERSION = 5\.0;/);
      }
    }
    configContainsSwiftVersion('Debug-Local');
    configContainsSwiftVersion('Release-Local');
  });
});
